apiVersion: backup.kafka.io/v1alpha1
kind: Backup
metadata:
  name: continuous-backup
  namespace: kafka
  labels:
    io.kannika/data-retention-policy: Keep
spec:
  source: my-kafka-cluster
  sink: s3-backup-storage
  
  topicSelectors:
    matchers:
      - glob: "orders.*"
      - glob: "payments.*"
      - name: "user-events"
  
  workGroup:
    workers: 3
    seed: 42
  
  compression: true
  batchSize: 5000
  flushInterval: "60s"
  
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"